remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Wirefox
logo: logo.png
description: Wirefox is a dead simple headless proxy device for SecOps and Pentesters.
show_downloads: true
